version: '3.1'
services:

  db:
    image: postgres
    restart: always
    networks:
      - eventapi
    environment:
      POSTGRES_USER: ${EVENT_DB_USER}
      POSTGRES_PASSWORD: ${EVENT_DB_PASSWORD}
      POSTGRES_DB: ${EVENT_DB_DATABASE}
    ports:
      - ${EVENT_DB_PORT}:${EVENT_DB_PORT}
  app: 
    image: node:16.14.0
    restart: unless-stopped
    container_name: eventapi
    working_dir: /usr/src/app
    networks:
      - eventapi
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/usr/src/app
      - ./.volumes/logs:/root/.npm/_logs
    command: bash -c "npm run docker:start"
    depends_on:
    - db

networks:
  eventapi:
    driver: bridge